/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconArrowDownBold: typeof import('@element-plus/icons-vue')['ArrowDownBold']
    ElIconArrowUpBold: typeof import('@element-plus/icons-vue')['ArrowUpBold']
    ElIconDownload: typeof import('@element-plus/icons-vue')['Download']
    ElIconHelp: typeof import('@element-plus/icons-vue')['Help']
    ElIconMinus: typeof import('@element-plus/icons-vue')['Minus']
    ElIconNotebook: typeof import('@element-plus/icons-vue')['Notebook']
    ElIconPlus: typeof import('@element-plus/icons-vue')['Plus']
    ElIconRight: typeof import('@element-plus/icons-vue')['Right']
    ElIconSetting: typeof import('@element-plus/icons-vue')['Setting']
    ElIconSort: typeof import('@element-plus/icons-vue')['Sort']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ExportDialog: typeof import('./src/components/ExportDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingDrawer: typeof import('./src/components/SettingDrawer.vue')['default']
    SettingPremisesDialog: typeof import('./src/components/SettingPremisesDialog.vue')['default']
    ShowSqlDialog: typeof import('./src/components/ShowSqlDialog.vue')['default']
    TextPanel: typeof import('./src/components/TextPanel.vue')['default']
    ToolBox: typeof import('./src/components/ToolBox.vue')['default']
    TreeDataNode: typeof import('./src/components/TreeDataNode.vue')['default']
    TreeDataNodePanel: typeof import('./src/components/TreeDataNodePanel.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
